insert into public.app_settings (key, value, updated_at)
select 'server.publicBaseUrl', value, now()
from public.app_settings
where key = 'email.passwordResetBaseUrl'
on conflict (key) do nothing;

insert into public.message_templates (key, namespace, required_params, active, created_at, updated_at)
values
  ('push.titles.dailyAnswerWaiting', 'push', '{}', true, now(), now()),
  ('push.titles.dailyRevealed', 'push', '{}', true, now(), now()),
  ('push.titles.questWaitingConfirmation', 'push', '{}', true, now(), now()),
  ('push.titles.questCompleted', 'push', '{}', true, now(), now()),
  ('push.titles.loveJarNote', 'push', '{}', true, now(), now()),
  ('push.titles.memoryCreated', 'push', '{}', true, now(), now()),
  ('push.titles.knowMeQuestion', 'push', '{}', true, now(), now()),
  ('push.titles.knowMeAnsweredHit', 'push', '{}', true, now(), now()),
  ('push.titles.knowMeAnsweredMiss', 'push', '{}', true, now(), now()),
  ('push.titles.coupleDisconnected', 'push', '{}', true, now(), now()),
  ('push.titles.coupleJoined', 'push', '{name}', true, now(), now()),
  ('push.bodies.dailyAnswerWaiting', 'push', '{name}', true, now(), now()),
  ('push.bodies.dailyRevealed', 'push', '{}', true, now(), now()),
  ('push.bodies.questWaitingConfirmation', 'push', '{name,title}', true, now(), now()),
  ('push.bodies.questCompleted', 'push', '{title}', true, now(), now()),
  ('push.bodies.loveJarNote', 'push', '{name}', true, now(), now()),
  ('push.bodies.memoryCreated', 'push', '{name,title}', true, now(), now()),
  ('push.bodies.knowMeQuestion', 'push', '{name}', true, now(), now()),
  ('push.bodies.knowMeAnsweredHit', 'push', '{name}', true, now(), now()),
  ('push.bodies.knowMeAnsweredMiss', 'push', '{name}', true, now(), now()),
  ('push.bodies.coupleDisconnected', 'push', '{name}', true, now(), now()),
  ('push.bodies.coupleJoined', 'push', '{name}', true, now(), now()),
  ('push.titles.test', 'push', '{}', true, now(), now()),
  ('push.bodies.test', 'push', '{}', true, now(), now())
on conflict (key) do nothing;

insert into public.message_template_translations (template_key, locale, text, description, created_at, updated_at)
values
  ('push.titles.dailyAnswerWaiting', 'de', 'Antwort wartet', 'Push-Titel: Antwort wartet', now(), now()),
  ('push.titles.dailyRevealed', 'de', 'Eure Antworten sind sichtbar', 'Push-Titel: Tagesfrage freigeschaltet', now(), now()),
  ('push.titles.questWaitingConfirmation', 'de', 'Aufgabe wartet auf dich', 'Push-Titel: Aufgabe wartet auf Bestätigung', now(), now()),
  ('push.titles.questCompleted', 'de', 'Aufgabe abgeschlossen', 'Push-Titel: Aufgabe abgeschlossen', now(), now()),
  ('push.titles.loveJarNote', 'de', 'Ein neuer Zettel wartet', 'Push-Titel: Liebesglas-Zettel', now(), now()),
  ('push.titles.memoryCreated', 'de', 'Neue Erinnerung', 'Push-Titel: Erinnerung erstellt', now(), now()),
  ('push.titles.knowMeQuestion', 'de', 'Eine Kennst-du-mich-Frage wartet', 'Push-Titel: Kennst-du-mich-Frage', now(), now()),
  ('push.titles.knowMeAnsweredHit', 'de', 'Treffer im Kennst-du-mich-Spiel', 'Push-Titel: Kennst-du-mich richtig geraten', now(), now()),
  ('push.titles.knowMeAnsweredMiss', 'de', 'Eine Antwort ist da', 'Push-Titel: Kennst-du-mich falsch geraten', now(), now()),
  ('push.titles.coupleDisconnected', 'de', 'Paarung wurde getrennt', 'Push-Titel: Paarung getrennt', now(), now()),
  ('push.titles.coupleJoined', 'de', '{name} ist da', 'Push-Titel: Partner beigetreten', now(), now()),
  ('push.bodies.dailyAnswerWaiting', 'de', '{name} hat geantwortet. Jetzt fehlst noch du.', 'Push-Text: Antwort wartet', now(), now()),
  ('push.bodies.dailyRevealed', 'de', 'Ihr habt beide geantwortet. Eine neue Blume ist gewachsen.', 'Push-Text: Tagesfrage freigeschaltet', now(), now()),
  ('push.bodies.questWaitingConfirmation', 'de', '{name} hat "{title}" bestätigt. Du kannst jetzt abschließen.', 'Push-Text: Aufgabe wartet auf Bestätigung', now(), now()),
  ('push.bodies.questCompleted', 'de', 'Eure Aufgabe "{title}" hat euren Garten wachsen lassen.', 'Push-Text: Aufgabe abgeschlossen', now(), now()),
  ('push.bodies.loveJarNote', 'de', '{name} hat etwas in euer Liebesglas gelegt.', 'Push-Text: Liebesglas-Zettel', now(), now()),
  ('push.bodies.memoryCreated', 'de', '{name} hat "{title}" in eure Timeline gelegt.', 'Push-Text: Erinnerung erstellt', now(), now()),
  ('push.bodies.knowMeQuestion', 'de', '{name} hat eine Frage über sich gestellt. Was schätzt du?', 'Push-Text: Kennst-du-mich-Frage', now(), now()),
  ('push.bodies.knowMeAnsweredHit', 'de', '{name} hat dich richtig eingeschätzt.', 'Push-Text: Kennst-du-mich richtig geraten', now(), now()),
  ('push.bodies.knowMeAnsweredMiss', 'de', '{name} hat geraten. Ein neuer Gesprächsanlass ist da.', 'Push-Text: Kennst-du-mich falsch geraten', now(), now()),
  ('push.bodies.coupleDisconnected', 'de', '{name} hat das Konto gelöscht. Eure Paarung wurde getrennt.', 'Push-Text: Paarung getrennt', now(), now()),
  ('push.bodies.coupleJoined', 'de', '{name} hat deinen Paarraum betreten.', 'Push-Text: Partner beigetreten', now(), now()),
  ('push.titles.test', 'de', 'Herzgarten Test', 'Push-Titel: Testnachricht', now(), now()),
  ('push.bodies.test', 'de', 'Push-Benachrichtigungen sind aktiv.', 'Push-Text: Testnachricht', now(), now()),
  ('push.titles.dailyAnswerWaiting', 'en', 'Answer waiting', 'Push title: answer waiting', now(), now()),
  ('push.titles.dailyRevealed', 'en', 'Your answers are visible', 'Push title: daily question revealed', now(), now()),
  ('push.titles.questWaitingConfirmation', 'en', 'Quest waiting for you', 'Push title: quest awaiting confirmation', now(), now()),
  ('push.titles.questCompleted', 'en', 'Quest completed', 'Push title: quest completed', now(), now()),
  ('push.titles.loveJarNote', 'en', 'A new note is waiting', 'Push title: love jar note', now(), now()),
  ('push.titles.memoryCreated', 'en', 'New memory', 'Push title: memory created', now(), now()),
  ('push.titles.knowMeQuestion', 'en', 'A Know Me question is waiting', 'Push title: Know Me question', now(), now()),
  ('push.titles.knowMeAnsweredHit', 'en', 'Hit in the Know Me game', 'Push title: Know Me guessed correctly', now(), now()),
  ('push.titles.knowMeAnsweredMiss', 'en', 'An answer is in', 'Push title: Know Me guessed incorrectly', now(), now()),
  ('push.titles.coupleDisconnected', 'en', 'Pairing was disconnected', 'Push title: pairing disconnected', now(), now()),
  ('push.titles.coupleJoined', 'en', '{name} is here', 'Push title: partner joined', now(), now()),
  ('push.bodies.dailyAnswerWaiting', 'en', '{name} answered. Now it is your turn.', 'Push body: answer waiting', now(), now()),
  ('push.bodies.dailyRevealed', 'en', 'You both answered. A new flower has grown.', 'Push body: daily question revealed', now(), now()),
  ('push.bodies.questWaitingConfirmation', 'en', '{name} confirmed "{title}". You can complete it now.', 'Push body: quest awaiting confirmation', now(), now()),
  ('push.bodies.questCompleted', 'en', 'Your quest "{title}" helped your garden grow.', 'Push body: quest completed', now(), now()),
  ('push.bodies.loveJarNote', 'en', '{name} put something in your love jar.', 'Push body: love jar note', now(), now()),
  ('push.bodies.memoryCreated', 'en', '{name} added "{title}" to your timeline.', 'Push body: memory created', now(), now()),
  ('push.bodies.knowMeQuestion', 'en', '{name} asked a question about themselves. What is your guess?', 'Push body: Know Me question', now(), now()),
  ('push.bodies.knowMeAnsweredHit', 'en', '{name} guessed you correctly.', 'Push body: Know Me guessed correctly', now(), now()),
  ('push.bodies.knowMeAnsweredMiss', 'en', '{name} guessed. A new conversation starter is here.', 'Push body: Know Me guessed incorrectly', now(), now()),
  ('push.bodies.coupleDisconnected', 'en', '{name} deleted the account. Your pairing was disconnected.', 'Push body: pairing disconnected', now(), now()),
  ('push.bodies.coupleJoined', 'en', '{name} joined your couple space.', 'Push body: partner joined', now(), now()),
  ('push.titles.test', 'en', 'Herzgarten Test', 'Push title: test notification', now(), now()),
  ('push.bodies.test', 'en', 'Push notifications are active.', 'Push body: test notification', now(), now())
on conflict (template_key, locale) do nothing;
