export const loveJarTemplates = [
  'Ich liebe an dir ...',
  'Danke, dass du ...',
  'Mein liebster Moment mit dir war ...',
  'Ich freue mich mit dir auf ...',
  'Gutschein fuer ...',
  'Heute moechte ich dir sagen ...',
  'Du hast meinen Tag leichter gemacht, weil ...',
  'Ich musste an dich denken, als ...',
  'Eine kleine Sache, die ich an dir bewundere, ist ...',
  'Wenn wir bald Zeit haben, wuensche ich mir ...',
  'Mein Herzmoment der Woche mit dir war ...',
  'Ich fuehle mich dir nah, wenn ...',
  'Eine Erinnerung, die ich gern wiederholen wuerde, ist ...',
  'Ich bin stolz auf uns, weil ...',
  'Gutschein fuer einen Abend ohne Handy: ...',
  'Heute schenke ich dir diesen Gedanken: ...',
  'Was du vielleicht zu selten hoerst: ...',
  'Ich freue mich auf unser naechstes ...',
  'Ein kleines Versprechen fuer diese Woche: ...',
  'Du bringst mich zum Laecheln, wenn ...',
  'Ich moechte dir bald wieder zeigen, dass ...',
  'Ein Wunsch fuer uns beide: ...',
  'Danke fuer deine Geduld bei ...',
  'Ich fuehle mich sicher mit dir, wenn ...',
  'Ein Mini-Date, das ich gern mit dir haette: ...',
  'Was ich an unserem Alltag liebe: ...',
];
